import {
  ArrowDownAZ,
  ArrowUpDown,
  Copy,
  Eye,
  EyeOff,
  Gauge,
  Info,
  ListChecks,
  ListFilter,
  Paintbrush,
  Ruler,
  Settings2,
  Trash2,
  ToggleRight,
  Type,
} from "lucide-react";

export const KB_PROPERTY_UI_ICONS = {
  description: Info,
  display: Paintbrush,
  duplicate: Copy,
  filter: ListFilter,
  grouping: ListChecks,
  hidden: EyeOff,
  layout: Settings2,
  rating: Gauge,
  scale: Ruler,
  showValue: ToggleRight,
  sort: ArrowUpDown,
  sortDirection: ArrowDownAZ,
  type: Type,
  visibility: Eye,
  delete: Trash2,
} as const;
